name: Deploy to Web Server

on:
  push:
    branches:
      - live-version

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.0
        registry-url: 'https://registry.yarnpkg.com/'

    - name: Install dependencies
      run: yarn install

    - name: Build Angular app
      run: yarn build --configuration="production"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: FTP Transfer
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist
        remote-dir: /path/on/server
