name: Deploy to Web Server

on:
  push:
    branches:
      - live-version

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.0
        registry-url: 'https://registry.yarnpkg.com/'

    - name: Install dependencies
      run: yarn install

    - name: Build Angular app
      run: yarn build --configuration="production"
      
    - name: Print contents of dist directory
      run: ls -R  
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Archive artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist
        
    - name: Show ENV_VARIBLES
      run: echo  ${{ secrets.FTP_SERVER }}

      

    - name: FTP Transfer
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp://getluck.fun
        username: u565128292
        password: M{y224>E9Q_g
        local-dir: ./getlucky-app/browser/
        remote-dir: public_html/
