name: Deploy to Web Server

on:
  push:
    branches:
      - live-version

env:
  FTP_SERVER: ${{secrets.FTP_SERVER}}
  FTP_USERNAME: ${{secrets.FTP_USERNAME}}
  FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
  FTP_DIR: ./

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.0
        registry-url: 'https://registry.yarnpkg.com/'

    - name: Install dependencies
      run: yarn install

    - name: Build Angular app
      run: yarn build --configuration="production"
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist

    # - name: FTP Transfer
    #   run: mkdir dummy_folder; cd dummy_folder; touch some_file.txt

    - name: FTP Transfer
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{env.FTP_SERVER}}
        username: ${{env.FTP_USERNAME}}
        password: ${{env.FTP_PASSWORD}}
        local-dir: ./getlucky-app/browser/
        # local-dir: ./dummy_folder/
        remote-dir: ${{env.FTP_DIR}}
        clean: true
